package com.example.whitepagesdemo.entities.response;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

@JsonIgnoreProperties(ignoreUnknown = true)
public class EmailAddressCheck {

    @JsonProperty("error")
    private Error error;

    @JsonProperty("warnings")
    private String[] warnings;

    @JsonProperty(value = "is_valid", required = true)
    private boolean isValid;

    private String[] diagnostics;

    @JsonProperty("is_autogenerated")
    private Boolean isAutogenerated;

    @JsonProperty("is_disposable")
    private Boolean isDisposable;

    @JsonProperty("email_to_name")
    private String emailNameMatch;

    @JsonProperty("registered_name")
    private String registeredName;

    @JsonProperty("registered_owner_age_range")
    private String registeredOwnerAgeRange;

    @JsonProperty("email_first_seen_date")
    private Date emailFirstSeenDate;

    @JsonProperty("email_first_seen_days")
    private Integer emailFirstSeenDays;

    @JsonProperty("email_domain_creation_date")
    private Date emailDomainCreationDate;

    @JsonProperty("email_domain_creation_days")
    private Integer emailDomainCreationDays;

}
